version: "3.9"

services:
    app:
        image: "mult"
        networks:
            default:
        ports:
            - "8080:8080"
        volumes:
            - /home/username/.config/simple-multiplexer:/root/.config/simple-multiplexer
        command: ./simple_multiplexer start
networks:
    default:
        driver: bridge